file:
  upload-dir: ./tmp/uploads

aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  sqs:
    queue-name: ${AWS_SQS_PDF_QUEUE_NAME}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_S3_REGION}